CC      = gcc
PROF    =
NOCRYPT = -lcrypt 
#C_FLAGS = -O2 -Wall $(PROF) $(NOCRYPT)
C_FLAGS = -Wall $(PROF) -DMERC -Dlinux -Os -ggdb3
L_FLAGS = -Os $(PROF) $(NOCRYPT)

O_FILES = act_comm.o act_info.o act_move.o act_obj.o act_wiz.o comm.o const.o \
          db.o fight.o handler.o interp.o magic.o save.o special.o update.o \
          kav_wiz.o kav_fight.o kav_info.o clan.o more.o \
          home.o rot_wiz.o demon.o werewolf.o olc.o string.o \
          bit.o core.o board.o desc_map.o changes.o

merc: $(O_FILES)
	rm -f godwars
	chmod g+w $(O_FILES)
	$(CC) $(L_FLAGS) -o godwars $(O_FILES)

clean:
	rm -fr godwars *.o *.c~ *.h~

.c.o: merc.h
	$(CC) -c $(C_FLAGS) $<
